### ISSUE TITLE
Does not "turn on" application inside ESP32 and after turned on, does not work at all

### ISSUE THREAD

**Issue by romrp** [victorbegha/easylifter-referee#1]
Hello,

To turn on, I have been connection with putty to com port, it will show the messages that is starting the AP, etc. After that, with the ESP32 "working", it will allow connection between the electron app and the router. Then you are able to connect to the IP as a referee, but the controls at the referee side are not working, i.e., you cannot turn on the chronometer or cast a vote.
Are you sure this is a working prototype? could you please post a video with it working?

Thank you and all the best,

Rom Pereira

PS.: could not make it work on mac or linux.

**Comment by victorbegha** [comment]
Hello Rom!

Yes, it is working. We recently used the system (as is) in our state bench press and deadlift competition. I'll work on posting videos from that meet later on.

Can you please give me the following information:

1- When you connect the router, does the status change to "Router connected" in green, on the top of the dashboard?

2- Have you installed the correct drivers (CP210x or CH34x depending on which ESP32 module you're using)?

3- On the referee side, does the status show as "Connected" below the buttons?

4- When you press one of the colored buttons as a referee, does a checkmark appear on that button?

5- What's the operating system and version of your phone? Which browser are you using?

I should say I've only tested this on Windows, so I don't have any information on any differences on Mac and Linux. But I'll try to help as much as I can based on these questions. Thank you.

**Comment by victorbegha** [comment]
(accidentally closed the issue, just reopened it. Please see the comment I left above, thank you)

**Comment by romrp** [comment]
> Hello Rom!
> 
> Yes, it is working. We recently used the system (as is) in our state bench press and deadlift competition. I'll work on posting videos from that meet later on.

Thank you.

> 
> Can you please give me the following information:
> 
> 1- When you connect the router, does the status change to "Router connected" in green, on the top of the dashboard?

if I just connect the ESP32 to the computer and "ncm start run" it says that is connected, but it does not create the referee wifi network. If I connect to the COM port with Putty first, apparently it post to the serial port and start. I even tried with the options serial debug = true and fixed com port on config.json file to try to debug the info. If I do not connect and disconnect to the device via putty first, the device app does not work.
 
> 
> 2- Have you installed the correct drivers (CP210x or CH34x depending on which ESP32 module you're using)?
> 

Yes, it is connecting to windows fine, I can upload the files with Arduino IDE.

> 3- On the referee side, does the status show as "Connected" below the buttons?

I will check it tonight.

> 
> 4- When you press one of the colored buttons as a referee, does a checkmark appear on that button?

You mean if javascript is running. I do believe so. I did not see any complains in the js console.

> 
> 5- What's the operating system and version of your phone? Which browser are you using? 

it is an old iphone. I send you the data tonight.

> 
> I should say I've only tested this on Windows, so I don't have any information on any differences on Mac and Linux. But I'll try to help as much as I can based on these questions. Thank you.

I will update those answers later tonight, thank you for the prompt response.

**Comment by victorbegha** [comment]
Closed for inactivity.
